# ai/interview/question_bank.py
# Why this file exists: Centralises all question templates so the generator
# just picks, fills placeholders, and returns. Adding new questions means
# editing only this file — nothing else changes.
# How it connects: Imported by generator.py. Templates use {skill},
# {company}, {project}, {years} as dynamic placeholders.
# Key concept: Questions are grouped by skill category AND difficulty,
# so we can generate a balanced set rather than 20 Python questions.

# ── Technical questions keyed by skill ──────────────────────────────────────
# Each entry is a list of (question_template, difficulty) tuples.
SKILL_QUESTIONS = {
    "python": [
        ("What is the difference between a list and a tuple in Python, and when would you use each?", "easy"),
        ("Explain how Python's GIL works and how it affects multithreading.", "medium"),
        ("How do Python decorators work? Write a decorator that measures function execution time.", "medium"),
        ("Explain the difference between `__str__` and `__repr__` in Python.", "easy"),
        ("What are Python generators and how do they differ from regular functions?", "medium"),
        ("How does Python's memory management and garbage collection work?", "hard"),
        ("Explain metaclasses in Python and give a practical use case.", "hard"),
        ("What is the difference between `deepcopy` and `copy` in Python?", "easy"),
        ("How would you implement a thread-safe singleton in Python?", "hard"),
        ("Explain asyncio and how async/await works in Python.", "medium"),
    ],
    "javascript": [
        ("What is the difference between `var`, `let`, and `const` in JavaScript?", "easy"),
        ("Explain event delegation and why it is useful.", "medium"),
        ("How does the JavaScript event loop work? Explain the call stack and task queue.", "medium"),
        ("What is a closure in JavaScript and give a practical example.", "medium"),
        ("Explain the difference between `==` and `===` in JavaScript.", "easy"),
        ("What are Promises and how do they differ from callbacks?", "medium"),
        ("Explain how prototypal inheritance works in JavaScript.", "hard"),
        ("What is the difference between `null` and `undefined`?", "easy"),
        ("How does `this` binding work in JavaScript? Give examples of each type.", "hard"),
        ("Explain the concept of hoisting in JavaScript.", "medium"),
    ],
    "node.js": [
        ("What is the Node.js event loop and how does it handle asynchronous operations?", "medium"),
        ("How do you handle errors in async/await functions in Node.js?", "easy"),
        ("What is the difference between `process.nextTick()` and `setImmediate()`?", "hard"),
        ("Explain how Node.js streams work and when you would use them.", "medium"),
        ("How would you prevent callback hell in a Node.js application?", "medium"),
        ("What is the purpose of the `cluster` module in Node.js?", "hard"),
        ("How do you implement middleware in Express.js?", "easy"),
        ("What is the difference between `require` and `import` in Node.js?", "easy"),
        ("How would you implement rate limiting in an Express API?", "medium"),
        ("Explain how JWT authentication works and implement it in Node.js.", "medium"),
    ],
    "react": [
        ("What is the difference between state and props in React?", "easy"),
        ("Explain the React component lifecycle and the useEffect hook.", "medium"),
        ("What is the virtual DOM and how does React use it?", "medium"),
        ("How do you optimise a React application to prevent unnecessary re-renders?", "hard"),
        ("Explain the difference between controlled and uncontrolled components.", "medium"),
        ("What are React hooks and why were they introduced?", "easy"),
        ("How does the Context API work and when would you use it over Redux?", "medium"),
        ("Explain lazy loading in React and how to implement it.", "medium"),
        ("What is React Fiber and how does it improve performance?", "hard"),
        ("How do you handle forms in React? Compare controlled vs uncontrolled approaches.", "medium"),
    ],
    "mongodb": [
        ("What is the difference between SQL and NoSQL databases? When would you choose MongoDB?", "easy"),
        ("Explain MongoDB's aggregation pipeline with an example.", "medium"),
        ("How do indexes work in MongoDB and how do you optimise query performance?", "medium"),
        ("What is the difference between embedded documents and references in MongoDB?", "easy"),
        ("How does MongoDB handle transactions? Explain ACID compliance.", "hard"),
        ("What is sharding in MongoDB and when would you use it?", "hard"),
        ("Explain the difference between `find()` and `aggregate()` in MongoDB.", "medium"),
        ("How do you model a many-to-many relationship in MongoDB?", "medium"),
        ("What are MongoDB Atlas features that help with scalability?", "easy"),
        ("How do you implement full-text search in MongoDB?", "medium"),
    ],
    "sql": [
        ("What is the difference between INNER JOIN, LEFT JOIN, and FULL OUTER JOIN?", "easy"),
        ("Explain database normalisation and the first three normal forms.", "medium"),
        ("What are indexes in SQL and how do they affect query performance?", "medium"),
        ("What is the difference between WHERE and HAVING clauses?", "easy"),
        ("Explain ACID properties in database transactions.", "medium"),
        ("Write a query to find the second highest salary from an employees table.", "medium"),
        ("What is a stored procedure and when would you use one?", "medium"),
        ("Explain the difference between clustered and non-clustered indexes.", "hard"),
        ("What is a window function in SQL? Give an example using ROW_NUMBER().", "hard"),
        ("How do you optimise a slow SQL query?", "hard"),
    ],
    "docker": [
        ("What is the difference between a Docker image and a Docker container?", "easy"),
        ("Explain how Docker networking works. What are bridge, host, and overlay networks?", "medium"),
        ("What is a Dockerfile and what are its most important instructions?", "easy"),
        ("How do Docker volumes work and why are they important?", "medium"),
        ("What is Docker Compose and how does it simplify multi-container applications?", "medium"),
        ("How do you optimise a Docker image to reduce its size?", "medium"),
        ("What is the difference between CMD and ENTRYPOINT in a Dockerfile?", "medium"),
        ("How do you implement health checks in Docker?", "hard"),
        ("Explain the difference between Docker Swarm and Kubernetes.", "hard"),
        ("How do you handle secrets and environment variables in Docker?", "medium"),
    ],
    "aws": [
        ("What is the difference between EC2, ECS, and Lambda?", "easy"),
        ("Explain how S3 storage classes work and when you would use each.", "medium"),
        ("What is AWS VPC and how do you set up a secure network architecture?", "medium"),
        ("How does auto-scaling work in AWS and what are its types?", "medium"),
        ("Explain the CAP theorem and how it applies to AWS services.", "hard"),
        ("What is the difference between SQS and SNS?", "easy"),
        ("How do you implement CI/CD using AWS CodePipeline?", "medium"),
        ("What is IAM and how do you implement least privilege access?", "medium"),
        ("Explain AWS CloudFormation and Infrastructure as Code.", "hard"),
        ("How do you monitor and debug serverless Lambda functions?", "medium"),
    ],
    "machine learning": [
        ("What is the difference between supervised and unsupervised learning?", "easy"),
        ("Explain bias-variance tradeoff in machine learning models.", "medium"),
        ("What is overfitting and how do you prevent it?", "medium"),
        ("Explain how gradient descent works.", "medium"),
        ("What is the difference between precision and recall? When would you optimise for each?", "medium"),
        ("Explain how a decision tree works and its limitations.", "easy"),
        ("What is cross-validation and why is it important?", "medium"),
        ("Explain the concept of feature engineering and give examples.", "medium"),
        ("What is the difference between bagging and boosting?", "hard"),
        ("How do you handle imbalanced datasets in machine learning?", "hard"),
    ],
    "deep learning": [
        ("What is the difference between a CNN and an RNN?", "medium"),
        ("Explain how backpropagation works.", "hard"),
        ("What is the vanishing gradient problem and how is it solved?", "hard"),
        ("Explain batch normalisation and why it speeds up training.", "medium"),
        ("What is transfer learning and when would you use a pre-trained model?", "medium"),
        ("What are attention mechanisms and how do transformers use them?", "hard"),
        ("What is dropout regularisation and how does it prevent overfitting?", "medium"),
        ("Explain the difference between ReLU, sigmoid, and tanh activation functions.", "medium"),
        ("How does an LSTM differ from a vanilla RNN?", "medium"),
        ("What is the purpose of word embeddings like Word2Vec and GloVe?", "medium"),
    ],
    "git": [
        ("What is the difference between `git merge` and `git rebase`?", "medium"),
        ("How do you revert a commit that has already been pushed to a remote branch?", "medium"),
        ("Explain the Git branching strategy your team uses.", "easy"),
        ("What is a Git stash and when would you use it?", "easy"),
        ("How do you resolve a merge conflict in Git?", "easy"),
        ("What is the difference between `git reset` and `git revert`?", "medium"),
        ("Explain the GitFlow workflow.", "medium"),
        ("What are Git hooks and how can they be used to enforce code quality?", "hard"),
    ],
    "default": [
        ("What is your experience with {skill}? Describe a project where you used it.", "easy"),
        ("What are the main advantages and disadvantages of {skill}?", "easy"),
        ("How do you stay up to date with developments in {skill}?", "easy"),
        ("Describe the most complex problem you solved using {skill}.", "medium"),
        ("How would you explain {skill} to a junior developer joining your team?", "medium"),
        ("What best practices do you follow when working with {skill}?", "medium"),
        ("Have you encountered any performance issues with {skill}? How did you resolve them?", "hard"),
        ("How does {skill} compare to its alternatives and when would you choose it?", "hard"),
    ],
}

# ── Experience-based questions ────────────────────────────────────────────────
EXPERIENCE_QUESTIONS = [
    ("Tell me about your role as {title} at {company}. What were your main responsibilities?", "easy", "experience"),
    ("What was the most challenging project you worked on at {company}?", "medium", "experience"),
    ("How did you handle a situation where you disagreed with a technical decision at {company}?", "medium", "experience"),
    ("Describe a time you improved a system's performance at {company}. What was the impact?", "hard", "experience"),
    ("With {years} years of experience, what is the biggest technical lesson you have learned?", "medium", "experience"),
    ("How have your responsibilities evolved over your {years} years of experience?", "easy", "experience"),
    ("Describe a time you had to learn a new technology quickly. How did you approach it?", "medium", "experience"),
    ("Tell me about a time you mentored a junior developer or helped a teammate grow.", "medium", "experience"),
]

# ── Project-based questions ───────────────────────────────────────────────────
PROJECT_QUESTIONS = [
    ("Walk me through the architecture of your {project} project.", "medium", "project"),
    ("What were the main technical challenges in building {project} and how did you solve them?", "hard", "project"),
    ("What would you do differently if you were to rebuild {project} from scratch today?", "hard", "project"),
    ("How did you ensure the scalability of {project}?", "hard", "project"),
    ("How did you test {project}? What testing strategies did you use?", "medium", "project"),
    ("What was your role in the {project} project — did you work alone or in a team?", "easy", "project"),
    ("How did you handle deployment and CI/CD for {project}?", "medium", "project"),
    ("What is the most important feature of {project} and why did you prioritise it?", "medium", "project"),
]

# ── Behavioral questions ──────────────────────────────────────────────────────
BEHAVIORAL_QUESTIONS = [
    ("Tell me about yourself and your journey into software development.", "easy", "behavioral"),
    ("Describe a time you missed a deadline. What happened and what did you learn?", "medium", "behavioral"),
    ("How do you prioritise tasks when you have multiple deadlines at the same time?", "medium", "behavioral"),
    ("Describe a time you received critical feedback. How did you respond?", "medium", "behavioral"),
    ("Tell me about a time you worked with a difficult team member. How did you handle it?", "medium", "behavioral"),
    ("Where do you see yourself in 3-5 years? How does this role fit your goals?", "easy", "behavioral"),
    ("Describe a situation where you had to make a decision with incomplete information.", "hard", "behavioral"),
    ("Tell me about a time you took ownership of a problem outside your job scope.", "medium", "behavioral"),
    ("How do you approach learning a completely unfamiliar technology?", "easy", "behavioral"),
    ("Describe a time you had to push back on a requirement from a stakeholder.", "hard", "behavioral"),
]